# The armor material that will be used for Custom Armors.
# Available Options:
# CHAINMAIL
# IRON
# GOLD
# DIAMOND
# NETHERITE
armor_material: NETHERITE # set to Netherite by default!

# Generate default armors config?
generate_default_textures: true # set to true by default!