name: Armament
version: '${version}'
main: dev.furq.armament.Armament
api-version: '1.20'
Author: ["Furq"]
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.0.20
commands:
  armament:
    description: Main command of the plugin
    usage: /armament <subcommand>
    permission: armament.admin